export const MODULE_ROLE_PERMISSIONS = {
  //   accountTypes: [
  //   // 'SUPER_ADMIN',
  //   // 'ADMIN',
  //   // 'TENANT_ADMIN',
  //   'EMPLOYEE',
  //   'REVIEWER',
  //   'ASSIGNER',
  // ] as const,

  modules: [
    {
      key: 'security',
      label: 'Security/Compliance',
      submodules: ['Dashboard', 'Framework', 'Controls', 'Evidence Task'],
      roles: {
        viewer: ['read'],
        editor: ['read', 'create', 'update'],
        manager: ['read', 'create', 'update', 'assign', 'approve'],
        admin: ['read', 'create', 'update', 'delete', 'manage'],
        auditor: ['read', 'export'],
      },
    },

    {
      key: 'operations',
      label: 'Operations',
      submodules: [
        'People',
        'Policy',
        'Procedure',
        'Training',
        'Finding Management',
        'Change Management',
        'Event Management',
        'Breach Management',
        'Incident Management',
        'NIS2',
        'NIS2 Self Assessment',
      ],
      roles: {
        viewer: ['read'],
        editor: ['read', 'create', 'update'],
        manager: ['read', 'create', 'update', 'assign', 'approve'],
        admin: ['read', 'create', 'update', 'delete', 'manage'],
        auditor: ['read', 'export'],
      },
    },

    // Add this block inside the modules array in roles-permissions.ts
// Place it after the 'operations' module block

{
  key: 'breach_email_notification',
  label: 'Breach Email Notification',
  submodules: ['Campaign', 'Recipients', 'Template', 'Remedies', 'Delivery'],
  roles: {
    viewer: ['read'],
    editor: ['read', 'upload'],
    manager: ['read', 'upload', 'configure'],
    admin: ['read', 'create', 'upload', 'configure', 'send', 'manage'],
  },
  permissions: {
    campaign: ['create', 'read'],
    recipients: ['upload', 'read'],
    template: ['read', 'edit'],
    remedies: ['read', 'edit'],
    preview: ['read'],
    send: ['trigger'],
    delivery: ['read'],
    audit_log: ['read'],
    settings: ['read', 'configure'],
  },
},

    {
      key: 'risk',
      label: 'Risk Management',
      submodules: [
        'Risk Assessment',
        'Cybersecurity',
        'Project',
        'Contract',
        'Menu',
        'Add New Menu',
        'All Menu List',
      ],
      roles: {
        viewer: ['read'],
        editor: ['read', 'create', 'update'],
        manager: ['read', 'create', 'update', 'assign', 'approve'],
        admin: ['read', 'create', 'update', 'delete', 'manage'],
        auditor: ['read', 'export'],
      },
    },

    // ✅ Vendor is now separate
    // {
    //   key: 'vendor',
    //   label: 'Vendor',
    //   submodules: [
    //     'Vendor Trust',
    //     'Vendor Details',
    //     'Vendor Questionnaire',
    //     'Vendor Login',
    //     'Engagements',
    //     'Contracts',
    //     'Findings',
    //     'Issues',
    //   ],
    //   roles: {
    //     viewer: ['read'],
    //     editor: ['read', 'create', 'update'],
    //     manager: ['read', 'create', 'update', 'approve', 'assign'],
    //     admin: ['read', 'create', 'update', 'delete', 'manage'],
    //     auditor: ['read', 'export'],
    //   },
    // },

    // ✅ TPRM is now separate
    {
      key: 'vendor',
      label: 'Vendor & Customer',
      submodules: [
        'Vendor Trust',
        'Vendor Details',
        'Vendor Questionnaire',
        'Vendor Login',
        'Engagements',
        'Contracts',
        'Findings',
        'Issues',
        'Customer Trust',
        'Client Management',
        'Reviewer Login',
      ],
      roles: {
        viewer: ['read'],
        editor: ['read', 'create', 'update'],
        manager: ['read', 'create', 'update', 'approve', 'assign'],
        admin: ['read', 'create', 'update', 'delete', 'manage'],
        auditor: ['read', 'export'],
      },
    },

    {
      key: 'tprm',
      label: 'Third Party Risk Management',
      submodules: [
        'Dashboard',
        'Committee Members',
        'Third Party Questionnaire',
        'Third Party Assessment',
        'Meeting Notes/Minutes',
        'Blacklisting',
        'Incident Portal',
        'Governance Approval',
        'Physical Audit',
        'SLA Management',
        'Findings/CAPA',
        'Reporting',
        'Third Party Login',
      ],
      roles: {
        viewer: ['read'],
        editor: ['read', 'create', 'update'],
        manager: ['read', 'create', 'update', 'approve', 'assign', 'review'],
        admin: [
          'read',
          'create',
          'update',
          'delete',
          'manage',
          'approve',
          'assign',
          'review',
          'export',
        ],
        auditor: ['read', 'review', 'audit', 'export'],
        reviewer: ['read', 'review', 'approve'],
      },
    },

    // ✅ Privacy is now separate
    {
      key: 'privacy',
      label: 'Privacy',
      submodules: [
        'Dashboard',
        'Frameworks',
        'DPIA / Appendix',
        'DPIA / Appendix Dashboard',
        'DPIA Templates',
        'All Assessments',
        'Review Queue',
        'Approval Queue',
        'Appendix',
        'Data Flow',
        'Data Mapping',
        'Mapping Dashboard',
        'BPA',
        'System Activities',
        'Data Flows',
        'Vendors',
        'Coverage',
        'ROPA',
        'Purpose',
        'Framework Mapping',
        'Framework Topics',
        'Framework Map',
        'Data Dictionary',
        'Data Dashboard',
        'Data Categories',
        'Data Classifications',
        'Data Subject Types',
        'Data Elements',
        'Purpose',
        'Retention Policies',
        'Retention Rules',
        'Reports',
        'Webform Consent',
        'Rights Management',
        'DSAR Dashboard',
        'Assignee Dashboard',
        'User Dashboard',
        'DSAR',
        'Cookie Consent Dashboard',
        'Websites',
        'Cookie Consent Management',
        'Child Consent',
        'Child Consent Dashboard',
        'Entities',
      ],
      roles: {
        viewer: ['read'],
        editor: ['read', 'create', 'update'],
        manager: ['read', 'create', 'update', 'approve', 'assign'],
        admin: ['read', 'create', 'update', 'delete', 'manage'],
        auditor: ['read', 'export'],
      },
    },

    // ✅ Scanner is already separate and should remain separate
    {
      key: 'scanner',
      label: 'Scanner',
      submodules: ['Data Inventory', 'Jobs', 'Scanner Config'],
      roles: {
        viewer: ['read'],
        editor: ['read', 'create', 'update'],
        manager: ['read', 'create', 'update', 'assign'],
        admin: ['read', 'create', 'update', 'delete', 'manage'],
        auditor: ['read', 'export'],
      },
      permissions: {
        dataInventory: ['read', 'create', 'update', 'delete'],
        jobs: ['read', 'create', 'update', 'delete', 'run'],
        scannerConfig: ['read', 'create', 'update', 'delete', 'manage'],
      },
    },

    {
      key: 'industry',
      label: 'Industry',
      submodules: [
        'Assessment',
        'Automobile',
        'TISAX',
        '6.0.3',
        'TISAX AUDIT',
        '6.0.3',
        'Assign Controls',
        'Assign Team',
        'ISO 42001',
        'Banking and Finance',
        'FFIEC',
        'CSCRF',
        'IRDA',
        'CRA',
        'RBI',
        'RBI Tracker',
        'RBI Tracker User Portal',
        'Healthcare',
      ],
      roles: {
        viewer: ['read'],
        editor: ['read', 'create', 'update'],
        manager: ['read', 'create', 'update', 'approve'],
        admin: ['read', 'create', 'update', 'delete', 'manage'],
        auditor: ['read', 'export'],
      },
    },

    {
      key: 'audit',
      label: 'Audit',
      submodules: [
        'Internal Audit',
        'Internal Audit - Reviewer',
        'Internal Audit - Approver',
        'Internal Audit - Auditor',
      ],
      roles: {
        viewer: ['read'],
        editor: ['read', 'create', 'update'],
        manager: ['read', 'create', 'update', 'approve'],
        admin: ['read', 'create', 'update', 'delete', 'manage'],
        auditor: ['read', 'export'],
      },
    },

    {
      key: 'grc',
      label: 'GRC as a Service',
      submodules: ['Dashboard', 'Average Dashboard', 'Detailed Dashboard'],
      roles: {
        viewer: ['read'],
        editor: ['read', 'create', 'update'],
        manager: ['read', 'create', 'update', 'approve', 'assign'],
        admin: ['read', 'create', 'update', 'delete', 'manage'],
        auditor: ['read', 'export'],
      },
    },

    {
      key: 'management_hub',
      label: 'Management Hub',
      submodules: [
        'Governance Hub',
        'Team Management',
        'Division Management',
        'Department Management',
        'Business Management',
        'Process Management',
        'Organization Management',
        'Meeting Management',
        'Compliance Hub',
        'Compliance Dashboard',
        'System Monitoring',
        'Audit Logs',
        'Notification Hub',
        'Notification Management',
        'Task Management Hub',
        'Create Task',
        'Task Summary',
        'Integration Hub',
        'Integration Management',
        'Asset Management',
        'Privacy',
        'Cookies Templates',
        'Consent Banner',
        'Install',
        'Scanner',
        'Privacy Consent Management',
        'Web Form Configuration',
        'Cookies Consent',
        'Banner Templates',
        'Cookie Consent Category',
        'Child Consent',
        'Config',
        'Settings',
      ],
      roles: {
        viewer: ['read'],
        admin: ['read', 'create', 'update', 'delete', 'manage'],
      },
    },

    {
      key: 'access_management',
      label: 'Access Management',
      submodules: [
        'Dashboard',
        'Role Management',
        'User Creation',
        'Assign Roles',
        'Tenant onboarding',
      ],
      roles: {
        viewer: ['read'],
        admin: ['read', 'create', 'update', 'delete', 'manage'],
      },
    },

    {
      key: 'privacy_consents',
      label: 'Privacy Consent Management',
      submodules: [
        'Web Form Configuration',
        'Cookies Consent',
        'Banner Templates',
        'Cookie Consent Category',
        'Child Consent',
        'Config',
      ],
      roles: {
        viewer: ['read'],
        admin: ['read', 'create', 'update', 'delete', 'manage'],
      },
    },

    {
      key: 'user_hub',
      label: 'User Hub',
      submodules: ['User Framework Portal', 'User Portal'],
      roles: {
        viewer: ['read'],
        admin: ['read', 'create', 'update', 'delete', 'manage'],
      },
    },

    {
      key: 'workbench',
      label: 'Workbench',
      submodules: [
        'Custom Workflow',
        'Form Builder',
        'Cybersecurity',
        'Response',
      ],
      roles: {
        viewer: ['read'],
        admin: ['read', 'create', 'update', 'delete', 'manage'],
      },
    },

    {
      key: 'EMPLOYEE',
      label: 'EMPLOYEE',
      submodules: [],
      roles: {
        viewer: [],
        admin: [],
      },
    },
    {
      key: 'REVIEWER',
      label: 'REVIEWER',
      submodules: [],
      roles: {
        viewer: [],
        admin: [],
      },
    },
    {
      key: 'ASSIGNER',
      label: 'ASSIGNER',
      submodules: [],
      roles: {
        viewer: [],
        admin: [],
      },
    },
    {
      key: 'CONSENT_DASHBOARD',
      label: 'Consent_Dashboard',
      submodules: [],
      roles: {
        viewer: [],
        admin: ['manage'],
      },
    },
    {
      key: 'mandate',
      label: 'Mandate Management',
      submodules: [
        'Mandate Dashboard',
        'Mandate Intake',
        'Mandate Review',
        'SMA Review',
        'Legal Review',
        'Controls Repository',
        'Control Audit',
      ],
      roles: {
        viewer: ['read'],

        editor: ['read', 'create', 'update', 'upload', 'extract'],

        manager: [
          'read',
          'create',
          'update',
          'upload',
          'extract',
          'assign',
          'notify',
          'workflow',
          'audit',
        ],

        admin: [
          'read',
          'create',
          'update',
          'delete',
          'manage',
          'upload',
          'extract',
          'assign',
          'notify',
          'workflow',
          'audit',
          'review.sma',
          'review.legal',
        ],

        auditor: ['read', 'audit', 'export'],

        sma: ['read', 'review.sma'],

        legal: ['read', 'review.legal'],
      },
    },
  ],
} as const;
